### ISSUE TITLE
Croos- origin error 

### ISSUE THREAD

**Issue by anuj-jaryal** [shoplemo/php-sdk#1]
I am getting this error 
![image](https://user-images.githubusercontent.com/28837176/101015354-4806d400-358d-11eb-88de-fc6a78145228.png)
![Screenshot from 2020-12-03 17-31-33](https://user-images.githubusercontent.com/28837176/101016009-3540cf00-358e-11eb-8e0f-399c27aa4dce.jpg)

**Comment by ozdemiremrah** [comment]
Hello, this case is about loading JS files from live environment for sandbox environment. You cannot experience this problem in a live environment.

**Comment by anuj-jaryal** [comment]
Hello there,
In 2nd image, why I getting that error.

**Comment by anuj-jaryal** [comment]
And I am getting this error in live environment. Can you see it on
http://poetryquotes.net/
